name: Lint

on:
  push:
    branches:
      - dom
      - sub
  pull_request:
    branches:
      - dom
      - sub

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run lint
      - run: cargo lint
    